version: "3.1"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    container_name: node-api
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: react-app
    stdin_open: true
    volumes:
      - ./my-app:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
